### ISSUE TITLE
Even after specifying emulator as target device it runs Tests on connected device and emulator both.

### ISSUE THREAD

**Issue by ziolitech** [Ghedeon/Testy#1]
Ran below command to test my instrumentation tests -:
./gradlew connectedAndroidTest -Pdevices=emulator-5554

**Comment by Ghedeon** [comment]
I should have marked this plugin as deprecated. 

The thing is that android team start rewriting some bits of gradle plugin in java, which breaks my plugin, based on groovy's metaClass feature. Would be nice of you to vote for the corresponding issue I opened an year ago: https://code.google.com/p/android/issues/detail?id=180700&thanks=180700&ts=1437571648
As you can see, they even fixed it, but it's just not pushed for release... you know.. for like 13 months already).

Meanwhile, give this snippet a try: https://gist.github.com/Ghedeon/79db271a91283f5a7109. It's been a while tho, chances a low.

**Comment by Turnsole** [comment]
After setting this up in my project, I noticed it wasn't working as well. 

Would you update your README file so this is obvious to folks?
